name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["hunter87ff/Spruce"]
assignees:
  - hunter87ff
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: server
    attributes:
      label: Discord Server Id
      description: Enter The Discord Server Id
      placeholder: "68135418234182387"
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue you are facing.
      placeholder: "Tell us what you see! and you can also share attachments here"
      value: "Tell us what you see! and you can also share attachments here"
    validations:
      required: true
      
  - type: dropdown
    id: perms
    attributes:
      label: Does it have required permissions
      multiple: true
      options:
        - "Yes"
        - "Not sure"
        - "No"
    validations:
      required: true


  # - type: input
  #   id: attachment
  #   attributes:
  #     label: Share Attachments
  #     description: Share attachment links, such as image, vide etc.
  #     placeholder: "https://example.com/image/7345927434234664/screenshot56.jpg"
  #   validations:
  #     required: false
      
  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Relevant log output
  #     description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
  #     render: shell
      
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
