blank_issues_enabled: false
contact_links:
  - name: Spruce Community Support
    url: https://github.com/Hunter87ff/Spruce/discussions
    about: Please ask and answer questions here.
  - name: Spruce Support
    url: https://sprucebot.tech
    about: Please report security vulnerabilities here.
