blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Hunter87ff/Spruce/discussions
    about: Please ask and answer questions here.
  - name: Spruce Support
    url: https://sprucbot.tech/support
    about: Please report security vulnerabilities here.
