name: Python App Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name
      
permissions:
  contents: read
  
env:
  token : ${{ secrets.TOKEN }}
  prefix : ${{ secrets.PREFIX }}
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./src  # Change this to your project's root directory

    - name: Deploy
      run: |
        # Add any deployment commands here
        # For example, to run your Python application:
        python main.py
