name: Deployment

on:
  # workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # - cron: '0 */6 * * *'
    - cron: '58 5 * * *'
    
permissions:
  contents: read
  
env:
  mongo_url  : ${{ secrets.MONGO_URL }}
  shards : ${{ secrets.SHARDS }}
  tkn : ${{ secrets.TKN }}
  prefix : ${{ secrets.PREFIX }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./src 
    - name: Install ffmpeg
      run: 
        sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Deploy
      run: |
        python src/main.py
