name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
    
permissions:
  contents: read
  
env:
  mongo_url  : ${{ secrets.MONGO_URL }}
  shards : ${{ secrets.SHARDS }}
  tkn : ${{ secrets.TKN }}
  prefix : ${{ secrets.PREFIX }}
  version : "2.0.5"
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9 

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Install OpenJDK from the AdoptOpenJDK distribution
        java-version: '17'
    
    - name: Verify Java version
      run: java -version

    - name: Update Credentials 
      run: |
        sed -i 's/^\(\s*clientId:\s*\).*/\1"${{ secrets.SPOT_ID }}"/' lava/application.yml
        sed -i 's/^\(\s*clientSecret:\s*\).*/\1"${{ secrets.SPOT_SECRET }}"/' lava/application.yml

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # sudo apt-get update && sudo apt install openjdk-17-jdk -y
      working-directory: ./src  
        
    # - name: Install ffmpeg
    #   run: 
    #     sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Deployment
      run: |
        python src/runner.py 
 
