name: Deployment

on:
  workflow_dispatch:
  # push:
    # branches:
    #   - main
    # paths:
    #   - 'src/**'
    
permissions:
  contents: read
  
env:
  mongo_url  : ${{ secrets.MONGO_URL }}
  shards : ${{ secrets.SHARDS }}
  tkn : ${{ secrets.TKN }}
  prefix : ${{ secrets.PREFIX }}
  version : "2.0.6"
  LOCAL_LAVA : true
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'
    
    - name: Verify Java version
      run: java -version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./src  
        
    # - name: Install ffmpeg
    #   run: 
    #     sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Deployment
      run: |
        python src/runner.py 
 
